[package]
name = "unified-diff"
version = "0.1.0"
authors = [
    "Michael Howell <michael@notriddle.com>",
    "The Rust Project Developers"
]
edition = "2018"

[[bin]]
name = "unified-diff"

[dependencies]
diff = "0.1.10"
