[workspace]
members = [
    "lib/unified-diff",
    "lib/context-diff",
    "lib/normal-diff",
    "bin/diff",
]

[package]
name = "diffutils"
version = "0.3.0"
authors = ["Michael Howell <michael@notriddle.com>"]
edition = "2018"

[dependencies]
context-diff = { path = "lib/context-diff", version = "0.3.0" }
normal-diff = { path = "lib/normal-diff", version = "0.3.0" }
unified-diff = { path = "lib/unified-diff", version = "0.3.0" }

[[bin]]
name = "diffutils"
path = "bin/main.rs"
