[package]
name = "diff"
version = "0.1.0"
authors = ["Michael Howell <michael@notriddle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
context-diff = { path = "../../lib/context-diff" }
normal-diff = { path = "../../lib/normal-diff" }
unified-diff = { path = "../../lib/unified-diff" }
